name: Playit VNC Tunnel

on:
  workflow_dispatch:

jobs:
  setup-vnc-tunnel:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install XFCE and x11vnc
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies x11vnc xvfb

    - name: Setup virtual display and start x11vnc
      run: |
        # Start X virtual framebuffer on display :1
        Xvfb :1 -screen 0 1280x720x16 &
        sleep 3
        # Start x11vnc server on display :1, no password, forever running
        x11vnc -display :1 -nopw -forever -shared &
        sleep 3

    - name: Create user for VNC login
      run: |
        sudo useradd -m afnex || echo "User afnex exists"
        echo "afnex:p@ssw0rd!" | sudo chpasswd
        sudo usermod -aG sudo afnex

    - name: Download and start Playit tunnel
      run: |
        mkdir -p ~/.config/playit_gg
        cd ~/.config/playit_gg
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x playit-linux-amd64
        mv playit-linux-amd64 playit
        # Run Playit and forward VNC port 5900 (adjust if needed)
        nohup ./playit --secret "${{ secrets.PL }}" --port 5900 &>/dev/null &
